### ISSUE TITLE
SSL Errors connecting to MariaDB

### ISSUE THREAD

**Issue by stevenwcarter** [BlackDex/rust-musl#12]
I'm not sure if this is an issue with this repo, or a problem with the MariaDB C Connector library, but starting with this commit 4a4da20690902232d834be8374dd97ed85ade59b I am receiving errors when trying to connect to a MariaDB server after building with `docker.io/blackdex/rust-musl:x86_64-musl-stable-1.82.0`.

```TLS/SSL error: SSL is required, but the server does not support it```

With no code changes, compiled within the previous stable release container (`docker.io/blackdex/rust-musl:x86_64-musl-stable-1.81.0`) everything works as usual.

**Comment by BlackDex** [comment]
@stevenwcarter thanks for reporting. 
I reverted back to v3.3.11. images are building as i typ.

**Comment by stevenwcarter** [comment]
Thanks, I've tested with the updated version and it is working again. My gut says this wasn't a problem with your setup, but rather something in the MariaDB C connector library or the Rust connector for it. Looking at the release notes for the C connector I saw a few changes related to SSL handling, but I haven't dug in.

Also, I want to say _thank you_ for creating this builder toolchain. I was banging my head against my desk about a year ago trying to get a musl build working with mysql/mariadb. This has been an absolute lifesaver. I also self-host VaultWarden, so thank you for that too!

**Comment by BlackDex** [comment]
It looks like it is a default setting which is changed.
https://jira.mariadb.org/plugins/servlet/mobile#issue/MDEV-31857

I have not yet tested it, but i suspect that is the issue. I'll probably set that to off too be able to use the newer version to keep it compatible.

**Comment by BlackDex** [comment]
I tried to use that setting, but it doesn't seem to keep the connection settings the same.

I am required to provide ssl_ca, and then it works. But that wasn't needed before.
So, it's not very upgrade-able friendly.

Will keep at 3.3.11 for now and see if i can figure out why this is the case now when i have more time.
